### PR TITLE
Dependencies

### PR DESCRIPTION
**Pull request by teddmason**

### CODE REVIEW

**Comment by teddmason** [comment]
@JFSCH John you alright to give this a review, it's a full sweep of dependency updates. However the standardjs update introduced a load of linting errors that needed sorting

**Review by JFSCH — DISMISSED** [review]
Looks OK to me.

**Comment by teddmason** [comment]
@JFSCH you alright to give a re-review for the issue fix

**Review by JFSCH — APPROVED** [review]
OK. Looks good.

**Pull request merged**
