### PR TITLE
FIS-696: Add bing location mocking.

### PR DESCRIPTION
**Pull request by JFSCH**
Bing location search api mocking

https://eaflood.atlassian.net/browse/FIS-696

In order to assist performance testing mock the Bing location search api calls.

### CODE REVIEW

**Comment by teddmason** [comment]
Reviewing...

**Comment by teddmason** [comment]
@JFSCH looks fine.  

Just wondering if we make a couple of additions to what we do in legacy, what are your thoughts on an additional warning at the head of each page to warn that mocking is in place on the service like the dummy data warning, so that we immediately know this is the case and don't have it trickle into a production service without noticing.

Also is it worth mocking out the external wreck requests in `util.js` so that we are certain that no external http requests are being made from the service. Although we'd need to ensure internal http requests are still being made to geoserver and the flood services.

Thoughts?

**Comment by JFSCH** [comment]
@teddmason Thanks for this. Really good points so happy to implement. There is a message in the console log indicating mocking is in place but I like the idea of the label at the head of each page.

**Comment by JFSCH** [comment]
@teddmason Latest changes committed display warning message as requested. Happy to change message description which is similar to the isDummyData warning. Still investigating mocking external requests in utils.js but debugging whilst testing suggests this may not be necessary as Bing location api call seems to be the only one.

**Review by teddmason — APPROVED** [review]

**Pull request merged**
